//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Main.h
//  @ Date : 2012/03/16
//  @ Author : 
//
//


#if !defined(_MAIN_H)
#define _MAIN_H


class Main {
public:
	int akicode_tbl;
	int codedata_tbl;
	int akicode_tbl_read();
private:
	int akicode_tbl_create();
};

#endif  //_MAIN_H
